'use strict';
const C=CVcrypto,$=id=>document.getElementById(id);
let account=null,profile=null,csrf='',mode='',results={},transfers=[],users=[],artifacts=null;
const blobUrls=new Set(),te=new TextEncoder();
const timing=(label,value)=>`${label}: ${(value*1000).toFixed(3)} ms`;
function notice(text,error=false){const target=$('auth').hidden?$('notice'):$('auth-status');target.textContent=text;target.className=error?'error':'success';}
async function api(path,data,method){
  const options={method:method||(data===undefined?'GET':'POST'),credentials:'same-origin',headers:{}};
  if(options.method!=='GET')options.headers['X-CSRF-Token']=csrf;
  if(data!==undefined){options.headers['Content-Type']='application/json';options.body=JSON.stringify(data);}
  const response=await fetch('/api/'+path,options),value=await response.json();
  if(!response.ok)throw Error(value.error+(value.elapsed_until_failure_seconds!==undefined?'\n'+timing('Elapsed until failure (server)',value.elapsed_until_failure_seconds):''));
  if(value.csrf)csrf=value.csrf;
  return value;
}
function bind(id,action){$(id).addEventListener('click',async()=>{const start=performance.now();$(id).disabled=true;try{await action();}catch(error){notice(error.message+'\n'+timing('Elapsed until failure',C.seconds(start)),true);}finally{$(id).disabled=false;}});}
function download(container,bytes,name,label='Download file'){
  const node=$(container);node.replaceChildren();const link=document.createElement('a'),url=URL.createObjectURL(new Blob([bytes],{type:'application/octet-stream'}));blobUrls.add(url);link.href=url;link.download=C.safeName(name);link.textContent=label;node.append(link);
}
function appendDownload(container,bytes,name,label){const link=document.createElement('a'),url=URL.createObjectURL(new Blob([bytes]));blobUrls.add(url);link.href=url;link.download=C.safeName(name);link.textContent=label;$(container).append(link);}
async function read(id,max=C.MAX){const file=$(id).files[0];if(!file)throw Error('Choose a file first.');if(file.size>max)throw Error(`File exceeds ${max} byte limit.`);return new Uint8Array(await file.arrayBuffer());}
async function keyFile(id){const bytes=await read(id,32);if(bytes.length!==32)throw Error('AES-256 key file requires exactly 32 raw bytes.');return bytes;}
function metricResult(r,operation){return [timing(operation+' workflow',r.seconds),timing('Raw AES '+operation.toLowerCase(),r.aes_seconds),timing(r.metadata.kdf==='RAW-KEY'?'Key-file import':'Password derivation',r.key_setup_seconds),timing('SHA-256',r.hash_seconds),`Original size: ${r.metadata.size} bytes`,`SHA-256: ${r.metadata.sha256}`,`AES throughput: ${r.aes_seconds>0?(r.metadata.size/1e6/r.aes_seconds).toFixed(3):'0'} MB/s (original bytes / 1,000,000 / AES seconds)`].join('\n');}
async function openArtifacts(){
  return new Promise((resolve,reject)=>{const request=indexedDB.open('CipherVault:'+account.id,1);request.onupgradeneeded=()=>request.result.createObjectStore('artifacts');request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(Error('Browser storage unavailable; downloads remain usable in this session.'));});
}
async function artifact(key,value){if(!artifacts)return null;return new Promise((resolve,reject)=>{const tx=artifacts.transaction('artifacts',value===undefined?'readonly':'readwrite'),store=tx.objectStore('artifacts'),request=value===undefined?store.get(key):store.put(value,key);request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(Error('Could not save encrypted output in browser storage.'));});}
async function save(kind,value){await api('results/'+kind,value);results[kind]=value;}
function page(name){document.querySelectorAll('.page').forEach(node=>node.hidden=node.id!=='page-'+name);document.querySelectorAll('nav button').forEach(node=>node.classList.toggle('active',node.dataset.page===name));window.scrollTo(0,0);}
document.querySelectorAll('[data-page]').forEach(node=>node.addEventListener('click',()=>page(node.dataset.page)));
function table(parent,rows){if(!rows.length)return;const wrap=document.createElement('div');wrap.className='table-wrap';const t=document.createElement('table'),head=document.createElement('tr'),keys=Object.keys(rows[0]).filter(k=>typeof rows[0][k]!=='object');for(const k of keys){const th=document.createElement('th');th.textContent=k;head.append(th);}t.append(head);for(const row of rows){const tr=document.createElement('tr');for(const k of keys){const td=document.createElement('td');td.textContent=typeof row[k]==='number'?Number(row[k].toFixed(6)):String(row[k]??'');tr.append(td);}t.append(tr);}wrap.append(t);parent.append(wrap);}
function csv(parent,rows,name){if(!rows.length)return;const keys=Object.keys(rows[0]).filter(k=>typeof rows[0][k]!=='object'),quote=x=>'"'+String(x??'').replaceAll('"','""')+'"',text=[keys.map(quote).join(','),...rows.map(r=>keys.map(k=>quote(r[k])).join(','))].join('\n');const a=document.createElement('a'),url=URL.createObjectURL(new Blob([text],{type:'text/csv'}));blobUrls.add(url);a.href=url;a.download=name+'.csv';a.textContent='Download measurements CSV';parent.append(a);}
function paragraph(parent,text){const p=document.createElement('p');p.textContent=text;parent.append(p);}
function plot(parent,title,series,xlabel,ylabel){
  const canvas=document.createElement('canvas');canvas.width=900;canvas.height=410;canvas.setAttribute('role','img');canvas.setAttribute('aria-label',title);parent.append(canvas);const x=canvas.getContext('2d'),all=series.flatMap(s=>s.points).filter(p=>p.every(Number.isFinite));if(!all.length)return;
  const left=85,right=865,top=60,bottom=310,maxY=Math.max(...all.map(p=>p[1]),.000001)*1.15,values=[...new Set(all.map(p=>p[0]))].sort((a,b)=>a-b),minX=values[0],maxX=values.at(-1),px=v=>left+(v-minX)/(maxX-minX||1)*(right-left),py=v=>bottom-v/maxY*(bottom-top),colors=['#38bdf8','#6ee7b7','#c4b5fd','#fbbf24'];
  x.fillStyle='#101a2a';x.fillRect(0,0,900,410);x.fillStyle='#e6edf6';x.font='20px system-ui';x.fillText(title,30,32);x.font='12px system-ui';x.strokeStyle='#344458';
  for(let i=0;i<=4;i++){const y=top+(bottom-top)*i/4;x.beginPath();x.moveTo(left,y);x.lineTo(right,y);x.stroke();x.fillText((maxY*(1-i/4)).toPrecision(3),8,y+4);}
  for(const value of values){const text=Number.isInteger(value)?String(value):value.toPrecision(3);x.fillText(text,px(value)-12,bottom+23);}
  x.fillText(xlabel,330,355);x.save();x.translate(20,265);x.rotate(-Math.PI/2);x.fillText(ylabel,0,0);x.restore();
  series.forEach((s,index)=>{x.strokeStyle=colors[index%colors.length];x.fillStyle=x.strokeStyle;x.beginPath();s.points.forEach((p,i)=>i?x.lineTo(px(p[0]),py(p[1])):x.moveTo(px(p[0]),py(p[1])));x.stroke();for(const p of s.points){x.beginPath();x.arc(px(p[0]),py(p[1]),4,0,Math.PI*2);x.fill();}x.fillText(s.name,60+index*240,390);});
}
function renderMeasurements(kind,value,target=null){
  if(kind==='hash_resistance'&&!target&&$('integrity-resistance-results'))renderMeasurements(kind,value,$('integrity-resistance-results'));
  const parent=target||$(kind+'-results');if(!parent)return;parent.replaceChildren();paragraph(parent,timing('Total measured analysis (Python server)',value.total_seconds));
  const rows=value.rows||[];
  if(kind==='benchmarks'){
    const configurations=[['AES encryption vs plaintext size','aes_encrypt_ms','Encryption','Duration (ms)'],['AES decryption vs plaintext size','aes_decrypt_ms','Decryption','Duration (ms)'],['SHA-256 vs plaintext size','sha256_ms','SHA-256','Duration (ms)'],['AES throughput vs plaintext size','aes_encrypt_MB_s','Encryption','Throughput (MB/s)']];
    for(const [title,field,label,unit]of configurations)plot(parent,title,[{name:label,points:rows.map(r=>[r.size_KiB,r[field]])}],'Plaintext size (KiB)',unit);
    plot(parent,'RSA-PSS signing / verification',[{name:'Signing',points:rows.map(r=>[r.size_KiB,r.rsa_sign_ms])},{name:'Verification',points:rows.map(r=>[r.size_KiB,r.rsa_verify_ms])}],'Plaintext size (KiB)','Duration (ms)');
    paragraph(parent,timing('RSA key generation, separate setup',value.key_generation_seconds)+'\nRSA curves exclude separately recorded file hashing. MB/s = bytes / 1,000,000 / seconds.');
    const vault=$('vault-graphs');vault.replaceChildren();plot(vault,'Encryption / decryption vs plaintext size',[{name:'Encryption',points:rows.map(r=>[r.size_KiB,r.aes_encrypt_ms])},{name:'Decryption',points:rows.map(r=>[r.size_KiB,r.aes_decrypt_ms])}],'Plaintext size (KiB)','Median AES duration (ms)');paragraph(vault,'Generated test plaintexts, medians of three trials. Larger inputs usually take more processing time; fluctuations can reflect timing noise.');
  }else if(kind==='password_lengths'){
    plot(parent,'Password characters vs encryption / decryption',[{name:'Encryption',points:rows.map(r=>[r.password_characters,r.encrypt_ms])},{name:'Decryption',points:rows.map(r=>[r.password_characters,r.decrypt_ms])}],'Password length (characters)','Median workflow duration (ms)');paragraph(parent,'Identical 1 MiB plaintext, three trials per password length. PBKDF2 uses 600,000 iterations and always derives a 256-bit AES key. Longer passwords do not add AES rounds; timings can remain similar. Character count alone does not establish password strength.');
  }else if(kind==='lengths'){
    for(const [field,label]of [['encrypt_ms','Encryption'],['decrypt_ms','Decryption']])plot(parent,label+' vs plaintext size',[128,192,256].map(bits=>({name:'AES-'+bits,points:rows.filter(r=>r.key_bits===bits).map(r=>[r.size_KiB,r[field]])})),'Plaintext size (KiB)','Median AES duration (ms)');
    const fixed=rows.filter(r=>r.size_bytes===1024*1024);plot(parent,'AES key length at fixed 1 MiB plaintext',[{name:'Encryption',points:fixed.map(r=>[r.key_bits,r.encrypt_ms])},{name:'Decryption',points:fixed.map(r=>[r.key_bits,r.decrypt_ms])}],'Key length (bits)','Median AES duration (ms)');paragraph(parent,'Analysis-only AES-128/192/256 comparison. File vault and transfer always use AES-256. Larger keys use more rounds, while hardware acceleration and measurement noise affect runtime.');
  }else if(kind==='avalanche'){
    plot(parent,'Single-bit changes vs ciphertext changes',['Plaintext bit flip','Key bit flip'].map(experiment=>({name:experiment,points:rows.filter(r=>r.experiment===experiment).map(r=>[r.flipped_bit,r.changed_percent])})),'Flipped bit position','Changed output bits (%)');
    paragraph(parent,timing('Random key setup',value.key_setup_seconds)+'\n'+timing('Baseline block encryption',value.baseline_encryption_seconds)+'\nPlaintext bit flips illustrate diffusion; key bit flips illustrate key sensitivity. This isolated single-block experiment never reuses GCM nonces. A small experiment does not prove security or guarantee 50% changes.');
  }else if(kind==='hash_resistance'){
    for(const field of ['median_attempts_used','median_search_ms']){plot(parent,field==='median_search_ms'?'Truncated SHA-256 search time':'Truncated SHA-256 attempts',['Preimage','Second preimage','Collision'].map(property=>({name:property,points:value.toy.filter(r=>r.property===property).map(r=>[r.retained_bits,r[field]])})),'Retained digest bits',field==='median_search_ms'?'Duration (ms)':'Attempts used');paragraph(parent,field==='median_search_ms'?'Actual median search times for deliberately shortened 8-, 12- and 16-bit digest prefixes. Timing varies with hardware and which candidates are found.':'Attempts used, capped by the search budget. Collision searches can match any two distinct candidates; preimage searches must match a fixed target. Capped searches may finish without finding a match.');}
    plot(parent,'Full SHA-256 · bounded search attempts',value.full.map((r,index)=>({name:r.property,points:[[index+1,r.attempts]]})),'Experiment index','Attempts used');
    paragraph(parent,'Full 256-bit SHA-256 uses the same bounded search budget. A failed search means no match was found among those candidates; it does not prove resistance. See the results table for success or failure.');
    plot(parent,'Theoretical generic SHA-256 work (not measured)',[{name:'log2 generic work',points:value.theory.map((r,index)=>[index+1,r.log2_generic_work])}],'1: preimage · 2: second preimage · 3: collision','log2 expected work');
    paragraph(parent,'Ideal-hash generic work estimates: about 2^256 attempts for preimages and ordinary second-preimage searches, versus 2^128 for collisions. These estimates are not measured by this experiment.');
    paragraph(parent,'Preimage: search for input matching a target digest. Second preimage: search for another input matching an existing file digest. Collision: search for any two distinct inputs sharing a digest. Truncated prefixes are deliberately weaker; failed budget-limited searches do not prove SHA-256 resistance. The theoretical graph shows generic work estimates, not experimental results.');
    table(parent,value.full.map(r=>({property:r.property,attempts:r.attempts,found:r.found,elapsed_ms:r.seconds*1000,hash_ms:r.hash_seconds*1000})));table(parent,value.toy);csv(parent,value.toy,kind);return;
  }
  table(parent,rows);csv(parent,rows,kind);
}
function renderVaultHistory(){const parent=$('vault-history');parent.replaceChildren();const rows=results.vault_metrics?.rows||[];if(!rows.length)return;plot(parent,'Your measured AES file operations',['Encryption','Decryption'].map(operation=>({name:operation,points:rows.filter(r=>r.operation===operation).map(r=>[r.size_bytes/1024,r.aes_ms]).sort((a,b)=>a[0]-b[0])})),'Original size (KiB)','AES duration (ms)');table(parent,rows);csv(parent,rows,'vault-operations');}
async function vaultMetric(result,operation){const rows=[...(results.vault_metrics?.rows||[]),{operation,size_bytes:result.metadata.size,key_method:result.metadata.kdf==='RAW-KEY'?'Key file':'Password',aes_ms:result.aes_seconds*1000,hash_ms:result.hash_seconds*1000,workflow_ms:result.seconds*1000}].slice(-100);await save('vault_metrics',{rows});renderVaultHistory();}
function formatStamp(value){const date=new Date(value);return value&&Number.isFinite(date.getTime())?new Intl.DateTimeFormat('en-GB',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit',second:'2-digit',fractionalSecondDigits:3,timeZoneName:'short'}).format(date):'Not recorded';}
function receiptFields(parent,title,entries){
  const section=document.createElement('section'),heading=document.createElement('h3'),list=document.createElement('dl');heading.textContent=title;list.className='receipt-fields';section.append(heading,list);
  for(const [label,value]of entries){const term=document.createElement('dt'),description=document.createElement('dd');term.textContent=label;description.textContent=value;list.append(term,description);}parent.append(section);
}
function signatureDetails(parent,signature,verified){const details=document.createElement('details'),summary=document.createElement('summary'),value=document.createElement('pre');summary.textContent='Digital signature · RSA-PSS / SHA-256 · Base64';value.textContent=signature;details.append(summary);paragraph(details,verified?'Receiver reports signature verified against the trusted signing fingerprint.':'Sender signature; awaiting recipient verification.');paragraph(details,'Signs the transfer manifest, which binds the encrypted package hash, original file hash, sender and recipient.');details.append(value);parent.append(details);}
function receiptTimings(parent,title,values,labels){const entries=Object.entries(values||{}).filter(([key,value])=>key.endsWith('_seconds')&&Number.isFinite(value)).map(([key,value])=>[labels[key]||key.replaceAll('_',' '),(value*1000).toFixed(3)+' ms']);receiptFields(parent,title,entries);}
async function refreshTransfers(){
  users=(await api('directory')).users;transfers=(await api('transfers')).transfers;
  $('recipient').replaceChildren();for(const user of users.filter(u=>u.user_id!==account.id)){const option=document.createElement('option');option.value=user.user_id;option.textContent=user.username;$('recipient').append(option);}
  $('inbox').replaceChildren();for(const row of transfers.filter(t=>t.recipient_id===account.id&&['sent','verified'].includes(t.status)&&Date.parse(t.expires_at)>Date.now())){const option=document.createElement('option');option.value=row.id;option.textContent=row.manifest.filename+' · from '+(users.find(u=>u.user_id===row.sender_id)?.username||row.sender_id);$('inbox').append(option);}
  const parent=$('transfer-list');parent.replaceChildren();
  for(const row of transfers){const item=document.createElement('article');item.className='transfer-item';const heading=document.createElement('h3');heading.textContent=row.manifest.filename;item.append(heading);const status=document.createElement('span');status.className='badge';status.textContent=Date.parse(row.expires_at)<=Date.now()?'Expired':row.receipt?'Verified recovery':row.status==='sent'?'Awaiting recovery':row.status;item.append(status);paragraph(item,`${row.sender_id===account.id?'Sent':'Inbox'} · ${row.manifest.size_bytes} bytes · ${users.find(u=>u.user_id===row.sender_id)?.username||'Sender'} → ${users.find(u=>u.user_id===row.recipient_id)?.username||'Recipient'}`);
    if(row.receipt)paragraph(item,'File successfully transferred and recovered (recipient report).');
    const grid=document.createElement('div');grid.className='receipt-grid';item.append(grid);
    receiptFields(grid,'Integrity & authenticity',[
      ['Original SHA-256',row.manifest.original_sha256],
      ['Recovered SHA-256',row.receipt?.sha256||'Awaiting recovery'],
      ['Hash comparison',row.receipt?(row.receipt.sha256===row.manifest.original_sha256?'MATCH':'MISMATCH'):'Pending'],
      ['RSA-PSS signature',row.receipt?.signature_valid?'VERIFIED (recipient report)':'Signed; pending recipient verification'],
      ['Sender signing fingerprint',row.fingerprint],
    ]);
    receiptFields(grid,'Transfer timeline',[
      ['Published · sender clock',formatStamp(row.manifest.published_at)],
      ['Stored · server clock',formatStamp(row.created_at)],
      ['Recovered · receiver clock',formatStamp(row.receipt?.recovered_at)],
      ['Receipt recorded · server clock',formatStamp(row.receipt?.recorded_at)],
      ['Expires',formatStamp(row.expires_at)],
    ]);
    receiptTimings(grid,'Sender timings',{...row.timings,...(row.upload_seconds!=null?{upload_seconds:row.upload_seconds}:{})},{aes_seconds:'AES encryption',encryption_seconds:'Encryption workflow',hash_seconds:'SHA-256 (file + package)',key_setup_seconds:'Password derivation',sign_seconds:'RSA-PSS signing',upload_seconds:'Upload + complete response'});
    if(row.receipt){receiptTimings(grid,'Receiver timings',row.receipt,{aes_seconds:'AES decryption',decrypt_seconds:'Decryption workflow',hash_seconds:'Recovered file SHA-256',network_seconds:'Download + complete response',receive_seconds:'Total receive & recovery',signature_seconds:'RSA-PSS verification'});paragraph(item,timing('Combined measured processing time',row.timings.encryption_seconds+row.timings.sign_seconds+(row.upload_seconds||0)+row.receipt.receive_seconds));paragraph(item,'Sum of encryption workflow, signing, upload and receive/recovery. Excludes signing-key unlock, metadata requests and time waiting for the receiver.');}
    signatureDetails(item,row.signature,!!row.receipt?.signature_valid);
    const zone=document.createElement('p');zone.className='muted';zone.textContent='Dates shown in '+Intl.DateTimeFormat().resolvedOptions().timeZone+'. Device clocks are not trusted timestamp-authority evidence.';item.append(zone);
    if(row.sender_id===account.id){const del=document.createElement('button');del.className='secondary';del.textContent='Delete transfer';del.onclick=async()=>{try{await api('transfers/'+row.id,undefined,'DELETE');await refreshTransfers();notice('Transfer deleted.');}catch(error){notice(error.message,true);}};item.append(del);}parent.append(item);
  }
  renderSummary();
}
function renderSummary(){const summary=$('summary');summary.replaceChildren();for(const [name,value]of [['Your transfers',transfers.length],['Verified receipts',transfers.filter(t=>t.receipt).length],['Benchmark sizes',results.benchmarks?.rows?.length||0]]){const card=document.createElement('article');card.className='card';const h=document.createElement('h2');h.textContent=String(value);card.append(h);paragraph(card,name);summary.append(card);}}
async function initialise(){
  const value=await api('session');csrf=value.csrf;account=value.user;profile=value.profile;mode=value.mode;
  $('auth').hidden=!!account;$('workspace').hidden=!account;if(!account)return;page('dashboard');
  $('mode').textContent=mode==='local'?'Local account demo':'Hosted account workspace';$('account-label').textContent=profile?.username||account.email;$('identity-setup').hidden=!!profile;$('my-fingerprint').textContent=profile?.fingerprint||'Create your signing identity first.';
  if(!value.ai_configured)$('ai-status').textContent='AI assistant is optional. Configure GEMINI_API_KEY on the server to enable real AI responses. All other features work without it.';
  results=(await api('results')).results;for(const [kind,value]of Object.entries(results))renderMeasurements(kind,value);renderVaultHistory();
  if(results.hash_metrics)$('hash-status').textContent='Saved hashing measurements:\n'+JSON.stringify(results.hash_metrics,null,2);
  if(results.signature_metrics)$('verify-status').textContent='Saved signature measurements:\n'+JSON.stringify(results.signature_metrics,null,2);
  try{artifacts?.close();artifacts=await openArtifacts();const saved=await artifact('encrypted');if(saved){download('encrypted-download',saved.package,saved.filename+'.cvault','Download previous encrypted package');$('encrypt-status').textContent='Restored encrypted output. Passwords and plaintext are not saved.';}}catch(error){notice(error.message,true);}
  await refreshTransfers();
}
const authHint=document.createElement('p');authHint.className='muted';authHint.textContent='Use 12–128 password characters. First time here? Create an account, then sign in.';$('account-password').after(authHint);
bind('register',async()=>{notice('Creating your account…');const result=await api('register',{email:$('email').value.trim(),password:$('account-password').value});$('account-password').value='';notice(result.message+'\n'+timing('Registration',result.operation_seconds));});
bind('login',async()=>{notice('Signing in…');const result=await api('login',{email:$('email').value.trim(),password:$('account-password').value});$('account-password').value='';await initialise();notice(timing('Sign-in',result.operation_seconds));});
bind('logout',async()=>{try{await api('logout',{});}finally{for(const url of blobUrls)URL.revokeObjectURL(url);blobUrls.clear();artifacts?.close();account=null;profile=null;results={};transfers=[];location.reload();}});
bind('enroll',async()=>{const start=performance.now(),identity=await C.generateIdentity($('new-signing-password').value,account.id);$('new-signing-password').value='';await api('identity',{username:$('username').value.trim(),public_key:identity.public_key,fingerprint:identity.fingerprint,wrapped_key:identity.wrapped_key});await initialise();notice([timing('RSA-3072 key generation',identity.key_seconds),timing('Private-key password derivation + encryption',identity.wrap_seconds),timing('Public-key SHA-256',identity.fingerprint_seconds),timing('Complete identity setup',C.seconds(start))].join('\n'));});
$('vault-method').onchange=()=>{$('vault-key-label').hidden=$('vault-method').value!=='Key file';$('vault-password-label').hidden=$('vault-method').value==='Key file';};
bind('encrypt',async()=>{ $('encrypted-download').replaceChildren();$('encrypt-status').textContent='';const file=$('vault-file').files[0],data=await read('vault-file'),key=$('vault-method').value==='Key file'?await keyFile('vault-key'):null,result=await C.encrypt(data,$('vault-password').value,file.name,key);$('vault-password').value='';if(key)key.fill(0);download('encrypted-download',result.package,result.metadata.filename+'.cvault','Download encrypted package');$('encrypt-status').textContent=metricResult(result,'Encryption');await artifact('encrypted',{package:result.package,filename:result.metadata.filename});await vaultMetric(result,'Encryption');notice('Encryption complete.');});
bind('decrypt',async()=>{ $('decrypted-download').replaceChildren();$('decrypt-status').textContent='';const packageBytes=await read('decrypt-file',C.MAX+4096),meta=C.parse(packageBytes).meta,key=meta.kdf==='RAW-KEY'?await keyFile('decrypt-key'):null;try{const result=await C.decrypt(packageBytes,$('decrypt-password').value,key);download('decrypted-download',result.data,result.metadata.filename,'Download recovered file');$('decrypt-status').textContent='Authentication succeeded · recovered hash matches\n'+metricResult(result,'Decryption');await vaultMetric(result,'Decryption');notice('Decryption complete.');}finally{$('decrypt-password').value='';if(key)key.fill(0);}});
bind('hash',async()=>{const data=await read('hash-file'),result=await C.hash(data);$('hash-status').textContent='SHA-256: '+result.value+'\n'+timing('Hash computation',result.seconds);await save('hash_metrics',{digest:result.value,hash_seconds:result.seconds,size_bytes:data.length});});
bind('compare',async()=>{const first=await read('hash-file'),second=await read('compare-file'),start=performance.now(),a=await C.hash(first),b=await C.hash(second),same=first.length===second.length&&first.every((v,i)=>v===second[i]),elapsed=C.seconds(start);$('hash-status').textContent=`Original SHA-256: ${a.value}\nComparison SHA-256: ${b.value}\nHashes match: ${a.value===b.value}\nBytes equal: ${same}\n${timing('Original hashing',a.seconds)}\n${timing('Comparison hashing',b.seconds)}\n${timing('Complete hash / byte comparison',elapsed)}`;await save('hash_metrics',{original_digest:a.value,comparison_digest:b.value,bytes_equal:same,comparison_seconds:elapsed,original_hash_seconds:a.seconds,comparison_hash_seconds:b.seconds});});
bind('hash-change',async()=>{const original=await read('hash-file');if(!original.length)throw Error('Select a nonempty file for the one-byte change demonstration.');const start=performance.now(),changed=original.slice();changed[0]^=1;const a=await C.hash(original),b=await C.hash(changed);$('hash-status').textContent=`Flipped one bit in the first byte.\nOriginal: ${a.value}\nModified: ${b.value}\n${timing('Original SHA-256',a.seconds)}\n${timing('Modified SHA-256',b.seconds)}\n${timing('Complete demonstration',C.seconds(start))}\nThis demonstrates sensitivity to changes, not a proof of collision resistance.`;});
async function unlocked(password){const identity=(await api('identity')).profile;if(!identity)throw Error('Create your signing identity first.');return C.unlockIdentity(identity,password,account.id);}
bind('export-public',async()=>{if(!profile)throw Error('Create your signing identity first.');appendDownload('my-fingerprint',te.encode(C.pem(C.un64(profile.public_key))),'public.pem','Download public key');});
bind('sign',async()=>{const data=await read('sign-file'),unlock=await unlocked($('sign-password').value);$('sign-password').value='';const hash=await C.hash(data),signed=await C.sign(data,unlock.key);download('signature-download',signed.signature,'file.sig','Download RSA-PSS signature');appendDownload('signature-download',te.encode(C.pem(C.un64(profile.public_key))),'public.pem','Download public key');$('sign-status').textContent=[timing('Private-key unlock',unlock.seconds),timing('Standalone SHA-256',hash.seconds),timing('RSA-PSS signing (browser API includes internal SHA-256)',signed.seconds),'SHA-256: '+hash.value].join('\n');await save('signature_metrics',{digest:hash.value,hash_seconds:hash.seconds,sign_seconds:signed.seconds,unlock_seconds:unlock.seconds});});
bind('verify',async()=>{const data=await read('verify-file'),signature=await read('verify-signature',512),publicBytes=C.readPem(new TextDecoder().decode(await read('verify-public',8192))),hash=await C.hash(data),verified=await C.verify(data,signature,publicBytes);$('verify-status').textContent=(verified.valid?'Signature VERIFIED':'Signature verification FAILED')+'\n'+timing('Standalone SHA-256',hash.seconds)+'\n'+timing('RSA-PSS verification (includes public-key import and internal hashing)',verified.seconds);await save('signature_metrics',{valid:verified.valid,hash_seconds:hash.seconds,verify_seconds:verified.seconds});});
bind('send',async()=>{
  const start=performance.now();for(const id of ['send-status','send-plaintext','send-ciphertext','send-signature'])$(id).textContent='';
  const recipient=$('recipient').value;if(!recipient)throw Error('The recipient must register and create a signing identity first.');
  const data=await read('send-file'),file=$('send-file').files[0],encrypted=await C.encrypt(data,$('send-password').value,file.name);$('send-password').value='';
  const unlock=await unlocked($('send-signing-password').value);$('send-signing-password').value='';const packageHash=await C.hash(encrypted.package),id=crypto.randomUUID(),manifest={id,sender_id:account.id,recipient_id:recipient,filename:encrypted.metadata.filename,size_bytes:data.length,package_bytes:encrypted.package.length,original_sha256:encrypted.metadata.sha256,package_sha256:packageHash.value,published_at:new Date().toISOString()},message=te.encode(JSON.stringify(manifest)),signed=await C.sign(message,unlock.key);
  const timings={encryption_seconds:encrypted.seconds,aes_seconds:encrypted.aes_seconds,hash_seconds:encrypted.hash_seconds+packageHash.seconds,sign_seconds:signed.seconds,key_setup_seconds:encrypted.key_setup_seconds};
  const draft=await api('transfers',{message:C.b64(message),signature:C.b64(signed.signature),timings}),uploadStart=performance.now();
  const response=await fetch(draft.upload_url,{method:draft.upload_method,headers:{'Content-Type':'application/octet-stream',...(draft.upload_url.startsWith('/')?{'X-CSRF-Token':csrf}:{'x-upsert':'false'})},body:encrypted.package});await response.arrayBuffer();if(!response.ok)throw Error('Encrypted upload failed. Delete the unfinished draft and retry.');
  const uploadSeconds=C.seconds(uploadStart);await api('transfers/'+id+'/publish',{upload_seconds:uploadSeconds});
  $('send-plaintext').textContent=C.preview(data);$('send-ciphertext').textContent=C.hex(C.parse(encrypted.package).cipher.slice(0,Math.min(data.length,256)))||'(empty plaintext)';$('send-signature').textContent=C.b64(signed.signature);
  $('send-status').textContent='File sent · awaiting recipient verification\nPublished (sender clock): '+formatStamp(manifest.published_at)+'\n'+metricResult(encrypted,'Encryption')+'\n'+timing('Package SHA-256',packageHash.seconds)+'\n'+timing('Signing-key unlock',unlock.seconds)+'\n'+timing('RSA-PSS signing (includes internal hashing)',signed.seconds)+'\n'+timing('Upload request + complete response',uploadSeconds)+'\n'+timing('Server signature verification',draft.server_signature_seconds)+'\n'+timing('Server signature prehash',draft.server_hash_seconds)+'\n'+timing('Complete preparation + upload + publish',C.seconds(start));await refreshTransfers();notice('Ciphertext sent. Share the password separately.');
});
bind('refresh-transfers',async()=>{await refreshTransfers();notice('Inbox and receipts refreshed.');});
bind('receive',async()=>{
  for(const id of ['receive-status','receive-ciphertext','receive-plaintext','receive-signature'])$(id).textContent='';$('receive-download').replaceChildren();
  const row=transfers.find(t=>t.id===$('inbox').value);if(!row)throw Error('Refresh your inbox and choose a transfer.');
  const expected=$('receive-fingerprint').value.trim().toLowerCase();if(!/^[a-f0-9]{64}$/.test(expected))throw Error('Enter the sender signing fingerprint verified through a trusted separate channel.');
  const start=performance.now(),networkStart=performance.now();let response=await fetch('/api/transfers/'+row.id+'/download');if(!response.ok)throw Error('Download denied or transfer expired.');
  if(response.headers.get('Content-Type').includes('application/json')){const info=await response.json();response=await fetch(info.download_url);if(!response.ok)throw Error('Private encrypted download failed.');}
  const packageBytes=new Uint8Array(await response.arrayBuffer()),networkSeconds=C.seconds(networkStart);
  if(packageBytes.length!==row.manifest.package_bytes||packageBytes.length>C.MAX+4096)throw Error('Received package size mismatch.');
  const publicHash=await C.hash(C.un64(row.public_key));if(publicHash.value!==expected||row.fingerprint!==expected)throw Error('Untrusted sender signing key.');
  const message=C.un64(row.message),manifest=JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(message)),packageHash=await C.hash(packageBytes),verified=await C.verify(message,C.un64(row.signature),C.un64(row.public_key));
  if(!verified.valid||manifest.id!==row.id||manifest.sender_id!==row.sender_id||manifest.recipient_id!==account.id||manifest.package_sha256!==packageHash.value)throw Error('Digital signature or package hash verification failed.');
  const meta=C.parse(packageBytes).meta;if(meta.sha256!==manifest.original_sha256||meta.filename!==manifest.filename||meta.size!==manifest.size_bytes)throw Error('Signed manifest does not match package metadata.');
  $('receive-ciphertext').textContent=C.hex(C.parse(packageBytes).cipher.slice(0,Math.min(meta.size,256)))||'(empty plaintext)';
  let recovered;try{recovered=await C.decrypt(packageBytes,$('receive-password').value);}finally{$('receive-password').value='';}
  const receiveSeconds=C.seconds(start),stamp=new Date().toISOString();download('receive-download',recovered.data,recovered.metadata.filename,'Download recovered file');$('receive-plaintext').textContent=C.preview(recovered.data);$('receive-signature').textContent=row.signature;
  $('receive-status').textContent='File successfully transferred and recovered\nRSA-PSS: VERIFIED against trusted signing fingerprint\nOriginal SHA-256: '+manifest.original_sha256+'\nRecovered SHA-256: '+recovered.sha256+'\nPublished (sender clock): '+formatStamp(manifest.published_at)+'\nRecovered (receiver clock): '+formatStamp(stamp)+'\n'+metricResult(recovered,'Decryption')+'\n'+timing('Signing public-key fingerprint SHA-256',publicHash.seconds)+'\n'+timing('Encrypted package SHA-256',packageHash.seconds)+'\n'+timing('RSA-PSS verification (includes import and hashing)',verified.seconds)+'\n'+timing('Download through complete response body',networkSeconds)+'\n'+timing('Total receive and recovery',receiveSeconds)+`\nNetwork throughput: ${(packageBytes.length/1e6/networkSeconds).toFixed(3)} MB/s (package bytes / 1,000,000 / network seconds)`;
  if(row.status!=='verified')try{await api('transfers/'+row.id+'/receipt',{sha256:recovered.sha256,signature_valid:true,network_seconds:networkSeconds,decrypt_seconds:recovered.seconds,aes_seconds:recovered.aes_seconds,hash_seconds:recovered.hash_seconds,signature_seconds:verified.seconds,receive_seconds:receiveSeconds,recovered_at:stamp});}catch(error){$('receive-status').textContent+='\nRecovery succeeded; sender receipt could not be recorded: '+error.message;}
  await refreshTransfers();notice('Recovery succeeded. Download the recovered file.');
});
document.querySelectorAll('[data-analysis]').forEach(button=>button.onclick=async()=>{const start=performance.now();button.disabled=true;try{notice('Running measured '+button.dataset.analysis+' experiment…');const data=button.dataset.analysis==='avalanche'?{block:$('analysis-block').value.trim()}:{},value=await api('analysis/'+button.dataset.analysis,data);results[button.dataset.analysis]=value.result;renderMeasurements(button.dataset.analysis,value.result);renderSummary();notice(timing('Analysis request + response',C.seconds(start)));}catch(error){notice(error.message+'\n'+timing('Elapsed until failure',C.seconds(start)),true);}finally{button.disabled=false;}});
bind('ask',async()=>{const start=performance.now(),result=await api('ai',{question:$('ai-question').value});$('ai-status').textContent=result.answer+'\n\n'+timing('AI response latency (provider)',result.response_latency_seconds)+'\n'+timing('Complete assistant request latency',C.seconds(start));});
initialise().catch(error=>{$('auth-status').textContent=error.message;notice(error.message,true);});
